INSERT INTO `ad_kategori_program` (`id_kategori_program`, `nama_kategori`, `deskripsi_kategori`, `id_pilar`, `status_kategori`) VALUES
('1', 'Beasiswa Sang Surya', 'Adalah program bantuan biaya pendidikan lanjutan Diploma dan S1', '1', '1'),
('2', 'Beasiswa Mentari', 'Adalah program bantuan biaya pendidikan 12 tahun (SD-SMP-SMA)', '1', '1'),
('3', 'Peduli Guru', 'Adalah program peningkatan kualitas dan kesejahtraan guru honorer, agama dan relawan pendidikan', '1', '1'),
('4', 'Save our School', 'Adalah program peningkatan mutu prasarana fisik Lembaga Pendidikan yang berkualitas, berupa perbaikan (renovasi) dan perlengkapan sekolah yang tidak layak menjadi lebih memadai', '1', '1'),
('5', 'Lazismu Goes to Campus', 'Adalah program pemberdayaan berbasis kampus atau komunitas untuk meningkatkan partisipasi mahasiswa dalam menggali gagasan kreatif dan merumuskan inovasi pemberdayaan sosial', '1', '1'),
('6', 'Peduli Kesehatan', 'Adalah program layanan masyarakat dalam memberikan pengobatan ringan, konsultasi penyuluan kesehatan', '2', '1'),
('7', 'SAUM (Sanitasi Untuk Masyarakat)', 'Adalah program bantuan renovasi dan pengadakan sarana umum khususnya MCK dan kebutuhan air', '2', '1'),
('8', 'Pemberdayaan UMKM', 'Adalah program pemberdayaan untuk mengembangkan potensi ekonomi keluarga dan masyarakat', '3', '1'),
('9', 'Rias Corner', 'Adalah program pelatihan untuk melahirkan perempuan-perempuan pelaku usaha di bidang rias dan kecantikan', '3', '1'),
('10', 'Tani Bangkit', 'Adalah program pemberdayaan petani melalui system pertanian terpadu dan ramah lingkungan', '3', '1'),
('11', 'Peternakan Masyarakat Madani', 'Adalah program pemberdayaan peternak agar memiliki daya saing dan meningkatkan kualitas harga ternak', '3', '1'),
('12', 'Da\'i Dakwah', 'Adalah program pengembangan sumber daya dai yang akan bertugas di daerah pedalaman atau 3T', '4', '1'),
('13', 'Pemberdayaan Difabel', 'Gerakan pemberdayaan penyandang disabilitas untuk mengupayakan pencapaian kesejahteraan sosial dengan menggali dan memperdalam kemampuan yang dimiliki serta mematangkan keterampilan.', '4', '1'),
('14', 'Sayangi Lansia', 'Merupakan program yang ditujukan untuk lanjut usia', '4', '1'),
('15', 'Back To Masjid', 'Adalah program menyemarakkan masjid sebagai pusat layanan, pembinaan dan pemberdayaan mayarakat ', '4', '1'),
('16', 'Bedah Rumah', 'Adalah program perbaikan/renovasi rumah hingga layak huni', '4', '1'),
('17', 'MSC (Muhammadiyah Senior Care)', 'Adalah program yang fokus memberikan perhatian dan pelayanan terhadap para lansia (tokoh persyarikatan) yang lama berkhidmat, dan berkontribusi terhadap kemajuan persyarikatan Muhammadiyah', '5', '1'),
('18', 'Pemberdayaan Difabel', 'Adalah program pemberdayaan dengan menggali dan mengembangkan potensi yang dimiliki para penyandang disabilitas', '5', '1'),
('19', 'Indonesia Terang', 'Adalah program pemberian listrik tenaga surya kepada masyarakat miskin di daerah yang belum terjangkau aliran listrik dari PLN', '5', '1'),
('20', 'Indonesia Siaga', 'Adalah program respons tanggap darurat dan pasca bencana mulai dari aktivitas search & resque, rekontruksi dan rehabilitasi', '5', '1'),
('21', 'Muhammadiyah AID', 'Adalah program respons tanggap darurat dan pasca bencana mulai dari aktivitas search & resque, rekontruksi dan rehabilitasi di level internasional', '5', '1'),
('22', 'Ramadhan Mencerahkan', 'Adalah program sosialisasi, edukasi dan distribusi ', '6', '0'),
('23', 'Kado Ramadhan', 'Adalah program bantuan bingkisan di bulan ramadhan', '6', '0'),
('24', 'Qurban untuk Kemanusiaan', 'Adalah program penerimaan hewan qurban untuk diolah dalam bentuk rendangmu yang bias disalurkan ke daerah bencana/kemanusiaan', '6', '0'),
('25', 'Mudikmu Aman', 'Adalah program kepedulian bagi pemudik untuk mendapatkan kemudahan dan kenyamanan dalam perjalanan mudik', '6', '0'),
('26', 'Lain-lain (Pendidikan)', 'Ajuan yang terkait pilar pendidikan tetapi belum tercantum di program Lazismu UMS', '1', '0'),
('27', 'Bantuan Kemanusiaan', 'Adalah program tanggap darurat bencana', '5', '1'),
('28', 'Lain-lain (Dakwah)', 'Ajuan yang terkait pilar dakwah tetapi belum tercantum di program Lazismu UMS', '4', '1'),
('29', 'Lain-lain (Kemanusiaan)', 'Ajuan yang terkait pilar kemanusiaan tetapi belum tercantum di program Lazismu UMS', '5', '1'),
('30', 'Operasional', 'Program internal', '6', '1'),
('31', 'Beasiswa Kader Sang Surya', 'Adalah beasiswa yang diberikan kepada mahasiswa yang saat ini masih aktif menempuh studi di UMS, dan orangtuanya (sebagai tulang punggung ekonomi keluarga) telah meninggal dunia sehingga kesulitan biaya dalam melanjutkan studi di UMS. Sebagai syarat tamba', '1', '1'),
('32', 'Kegiatan & Sarpras Keorganisasian', 'Kegiatan & Sarpras Keorganisasian', '4', '1');
