INSERT INTO `ad_program` (`id_program`, `id_kategori_program`, `nama_program`, `deskripsi_program`, `jenis_formulir`, `status_program`) VALUES
('1', '1', 'Beasiswa Keluarga Yatim UMS (S1)', '', '1', '1'),
('2', '1', 'Beasiswa Subsidi SPP', '', '1', '1'),
('3', '2', 'Beasiswa Keluarga Yatim UMS (TK-SMA)', '', '1', '1'),
('4', '2', 'Beasiswa Dhuafa (Mitra Sekolah Muhammadiyah)', '', '2', '1'),
('5', '3', 'Peduli Guru', '', '2', '1'),
('6', '4', 'Program Bedah Sekolah', '', '2', '1'),
('7', '5', 'Kegiatan Ormawa', '', '0', '1'),
('8', '5', 'Pengabdian Masyarakat', '', '3', '1'),
('9', '6', 'Pengobatan Gratis (Individu)', '', '1', '1'),
('10', '6', 'Pengobatan Gratis (Lembaga)', '', '2', '1'),
('11', '7', 'Bedah KMKW', '', '1', '1'),
('12', '7', 'PAM-MU', '', '1', '1'),
('13', '8', 'UMKM Award', '', '3', '1'),
('14', '8', 'Bantuan modal usaha', '', '3', '1'),
('15', '9', 'Pelatihan Rias/Barbershop', '', '3', '1'),
('16', '10', 'Pendampingan Kelompok Tani', '', '3', '1'),
('17', '11', 'Pendampingan Kelompok Ternak', '', '3', '1'),
('18', '12', 'Da\'i Mandiri', '', '3', '1'),
('19', '13', 'Pelatihan Difabel', '', '3', '1'),
('20', '13', 'Bantuan Alat Kesehatan', '', '1', '1'),
('21', '14', 'Sayangi Lansia', '', '1', '1'),
('22', '15', 'Bedah Mushola', '', '4', '1'),
('23', '15', 'Program Pengajian/Pelatihan/TPA (Berbasis Masjid)', '', '1', '1'),
('24', '16', 'Bedah Rumah', '', '1', '1'),
('25', '17', 'Santunan Jompo', '', '1', '0'),
('26', '17', 'Santunan Dhuafa', '', '1', '0'),
('27', '26', 'Lain-lain (Pendidikan)', 'Program pendidikan lain', '1', '0'),
('28', '27', 'Bantuan Bencana', 'Bantuan darurat bencana berupa uang atau barang', '0', '1'),
('29', '28', 'Lain-lain (Dakwah)', 'Ajuan yang terkait pilar dakwah tetapi belum tercantum di program Lazismu UMS', '0', '1'),
('30', '29', 'Lain-lain (Kemanusiaan)', 'Ajuan terkait kemanusaiaan yang belum tercantum pada program kemanusiaan', '1', '1'),
('31', '30', 'Operasional', 'Program Internal', '0', '1'),
('32', '31', 'Beasiswa Kader Sang Surya', 'Beasiswa kader ini diperuntukkan kepada mahasiswa yang orang tuanya meninggal saat menempuh studi', '1', '1'),
('33', '18', 'Peduli Difabel', 'Program Peduli Difabel', '1', '1'),
('34', '4', 'Program Bantuan Sarpras Sekolah', 'Bantuan Sarpras Sekolah', '2', '1'),
('35', '1', 'Beasiswa Kader Sang Surya', ' Adalah beasiswa yang diberikan kepada mahasiswa yang saat ini masih aktif menempuh studi di UMS, dan orangtuanya (sebagai tulang punggung ekonomi keluarga) telah meninggal dunia sehingga kesulitan biaya dalam melanjutkan studi di UMS. Sebagai syarat tamb', '1', '1'),
('36', '1', 'Lainnya', '-', '1', '1'),
('37', '2', 'Beasiswa Subsidi SPP Individu', '-', '1', '1'),
('38', '6', 'Program Bantuan Alat Kesehatan', '-', '1', '1'),
('39', '8', 'Program Pelatihan', '-', '3', '1'),
('40', '32', 'Kegiatan & Sarpras Keorganisasian', 'Kegiatan & Sarpras Keorganisasian', '0', '1');
