INSERT INTO `ad_syarat_program` (`id_syarat`, `id_program`, `syarat_program`) VALUES
('1', '1', 'Surat keterangan yang menunjukkan putra putri dosen / karyawan yang meninggal sebelum masa pensiun'),
('2', '1', 'Surat keterangan masih aktif di perguruan tinggi '),
('3', '2', 'Surat keterangan aktif kuliah pada semester 2 s.d. 7'),
('4', '2', 'Sudah terseleksi dibuktikan dengan surat rekomendasi ormawa (BEM/IMM/MENTORING) tingkat fakultas'),
('5', '2', 'Tidak berlaku untuk mahasiswa kedokteran'),
('6', '3', 'Surat keterangan yang menunjukkan putra putri dosen / karyawan yang meninggal sebelum masa pensiun'),
('7', '3', 'Surat keterangan aktif sekolah (PAUD/SD/SMP/SMA)'),
('8', '4', 'Mengetahui pimpinan Muhammadiyah setempat (daerah/cabang/ranting/ortom)'),
('9', '4', 'Surat bukti aktif sekolah (PAUD/SD/SMP/SMA)'),
('10', '5', 'Mengetahui pimpinan Muhammadiyah setempat (daerah/cabang/ranting/ortom)'),
('11', '5', 'Form analisa sekolah (format dapat diunduh pada link    )'),
('12', '5', 'Scan KTP guru yang bersangkutan'),
('13', '6', 'Mengetahui pimpinan Muhammadiyah setempat (daerah/cabang/ranting/ortom)'),
('14', '6', 'Proposal pembangunan'),
('15', '6', 'Foto kondisi saat ini'),
('16', '7', 'Proposal kegiatan'),
('17', '8', 'Proposal pengabdian masyarakat'),
('18', '9', 'Mengetahui pimpinan Muhammadiyah setempat (daerah/cabang/ranting/ortom)'),
('19', '10', 'Mengetahui pimpinan Muhammadiyah setempat (daerah/cabang/ranting/ortom)'),
('20', '11', 'Mengetahui pimpinan Muhammadiyah setempat (daerah/cabang/ranting/ortom)'),
('21', '11', 'Foto kondisi saat ini'),
('22', '12', 'Mengetahui pimpinan Muhammadiyah setempat (daerah/cabang/ranting/ortom)'),
('23', '12', 'Foto kondisi saat ini'),
('24', '13', 'Mengetahui pimpinan Muhammadiyah setempat (daerah/cabang/ranting/ortom)'),
('25', '13', 'Proposal analisa kelayakan usaha'),
('26', '14', 'Mengetahui pimpinan Muhammadiyah setempat (daerah/cabang/ranting/ortom)'),
('27', '14', 'Proposal analisa kelayakan usaha'),
('28', '15', 'Mengetahui pimpinan Muhammadiyah setempat (daerah/cabang/ranting/ortom)'),
('29', '15', 'Proposal kegiatan (pelatihan)'),
('30', '16', 'Mengetahui pimpinan Muhammadiyah setempat (daerah/cabang/ranting/ortom)'),
('31', '16', 'Proposal analisa kelayakan usaha'),
('32', '17', 'Mengetahui pimpinan Muhammadiyah setempat (daerah/cabang/ranting/ortom)'),
('33', '17', 'Proposal analisa kelayakan usaha'),
('34', '18', 'Mengetahui pimpinan Muhammadiyah setempat (daerah/cabang/ranting/ortom)'),
('35', '18', 'Proposal pendanaan'),
('36', '19', 'Mengetahui pimpinan Muhammadiyah setempat (daerah/cabang/ranting/ortom)'),
('37', '19', 'Proposal kegiatan'),
('38', '20', 'Mengetahui pimpinan Muhammadiyah setempat (daerah/cabang/ranting/ortom)'),
('39', '20', 'Foto kondisi saat ini'),
('40', '21', 'Mengetahui pimpinan Muhammadiyah setempat (daerah/cabang/ranting/ortom)'),
('41', '21', 'Scan Kartu Keluarga'),
('42', '22', 'Mengetahui pimpinan Muhammadiyah setempat (daerah/cabang/ranting/ortom)'),
('43', '22', 'Proposal rencana pembangunan'),
('44', '22', 'Foto kondisi saat ini'),
('45', '23', 'Mengetahui pimpinan Muhammadiyah setempat (daerah/cabang/ranting/ortom)'),
('46', '23', 'Proposal rencana anggaran'),
('47', '23', 'Foto kondisi saat ini'),
('48', '24', 'Mengetahui pimpinan Muhammadiyah setempat (daerah/cabang/ranting/ortom)'),
('49', '24', 'Scan Kartu Keluarga'),
('50', '24', 'Proposal rencana pembangunan'),
('51', '24', 'Foto kondisi saat ini'),
('53', '27', 'islam'),
('54', '27', 'muslim'),
('55', '32', 'Surat kematian orang tua'),
('56', '32', 'Scan KTP'),
('57', '32', 'Scan KTM'),
('58', '32', 'Scan KRS semester terbaru'),
('59', '32', 'Transkrip nilai yang dicetak di BAA (IPK min. 2,75)'),
('60', '32', 'Surat keterangan aktif organisasi mahasiswa atau Ortom Muh (IMM/HW/TSPM/PM/NA). Jika tidak ada silakan unggah pernyataan akan aktif apabila menerima beasiswa'),
('61', '32', 'Bukti Tagihan SPP dari Keuangan atau screenshot dari  STAR untuk semester terbaru'),
('62', '32', 'Surat pernyataan ketersediaan menjadi relawan Lazismu UMS (ditandatangani)'),
('63', '32', 'Surat keterangan dan surat pernyataan dapat diunduh di web lazismu.ums.ac.id');
