INSERT INTO `dt_kategori_penerima` (`id_kategori_penerima`, `id_dana_dari`, `ket_kategori_penerima`) VALUES
('1', 'Zakat', 'Fakir'),
('2', 'Zakat', 'Miskin'),
('3', 'Zakat', 'Muallaf'),
('4', 'Zakat', 'Riqab'),
('5', 'Zakat', 'Gharimin'),
('6', 'Zakat', 'Fi sabilillah'),
('7', 'Zakat', 'Ibnu Sabil'),
('8', 'Zakat', 'Amil'),
('9', 'Infaq Umum', 'Ekonomi'),
('10', 'Infaq Umum', 'Sosial'),
('11', 'Infaq Umum', 'Pendidikan'),
('12', 'Infaq Umum', 'Kesehatan'),
('13', 'Infaq Umum', 'Kemanusiaan'),
('14', 'Infaq Umum', 'Keagamaan'),
('15', 'Infaq Umum', 'CSR/Lainnya'),
('16', 'Infaq Umum', 'Amil'),
('17', 'Amil', 'Amil'),
('18', 'Infaq Terikat', 'Ekonomi'),
('19', 'Infaq Terikat', 'Sosial'),
('20', 'Infaq Terikat', 'Pendidikan'),
('21', 'Infaq Terikat', 'Kesehatan'),
('22', 'Infaq Terikat', 'Kemanusiaan'),
('23', 'Infaq Terikat', 'Keagamaan'),
('24', 'Infaq Terikat', 'CSR/Lainnya'),
('25', 'Infaq Terikat', 'Amil'),
('26', 'DSKL', 'Qurban'),
('27', 'DSKL', 'Rukba'),
('28', 'DSKL', 'Umra'),
('29', 'DSKL', 'Bagi Hasil DSKL'),
('30', 'DSKL', 'Hibah'),
('31', 'DSKL', 'Hadiyah'),
('32', 'DSKL', 'Tawidh'),
('33', 'DSKL', 'Diyat'),
('34', 'DSKL', 'Kafarat'),
('35', 'DSKL', 'Fidyah'),
('36', 'DSKL', 'Tazir'),
('37', 'DSKL', 'Dam');
